### ISSUE TITLE
"Unknown terminal type" error on macOS 10.12.3

### ISSUE THREAD

**Issue by wangpengmit** [cpitclaudel/esh#1]
I got this error when running "esh2tex some-file.tex" on macOS 10.12.3:

Starting ESH:
  done.
Loading "/Users/wangpeng/papers/timl/esh-init.el":
ESH error: (error "Unknown terminal type")
  esh-server--handle-error(error (error "Unknown terminal type"))
  make-terminal-frame(((display) (visibility)))
  tty-create-frame-with-faces(((display) (visibility)))
  make-frame(((display) (visibility)))
  esh-server-init(nil ("/Users/wangpeng/papers/timl/esh-init.el" 22746 47600 0 0))
  (progn (esh-server-init nil (quote ("/Users/wangpeng/papers/timl/esh-init.el" 22746 47600 0 0))))
  eval((progn (esh-server-init nil (quote ("/Users/wangpeng/papers/timl/esh-init.el" 22746 47600 0 0)))))

The EMACS env. var. is correctly set to /Applications/Emacs.app/Contents/MacOS/Emacs
The value of TERM is xterm-256color. I tried to use xterm and vt100 but without success.

**Comment by cpitclaudel** [comment]
Should be fixed :) Thanks for your help.  Can you give it a try?
